package ir.adicom.app.beginneridea.quiz

val countries = listOf(
    "Afghanistan", "Kabul",
    "Albania", "Tirana",
    "Algeria", "Algiers",
    "Andorra", "Andorra la Vella",
    "Angola", "Luanda",
    "Argentina", "Buenos Aires",
    "Armenia", "Yerevan",
    "Australia", "Canberra",
    "Austria", "Vienna",
    "Azerbaijan", "Baku",
    "Bahamas", "Nassau",
    "Bahrain", "Manama",
    "Bangladesh", "Dhaka",
    "Barbados", "Bridgetown",
    "Belarus", "Minsk",
    "Belgium", "Brussels",
    "Benin", "Porto-Novo",
    "Bermuda", "Hamilton",
    "Bhutan", "Thimphu",
    "Bolivia", "Sucre",
    "Bosnia and Herzegovina", "Sarajevo",
    "Botswana", "Gaborone",
    "Brazil", "Brasília",
    "Brunei", "Bandar Seri Begawan",
    "Bulgaria", "Sofia",
    "Burkina Faso", "Ouagadougou",
    "Burundi", "Bujumbura",
    "Cambodia", "Phnom Penh",
    "Cameroon", "Yaoundé",
    "Canada", "Ottawa",
    "Chad", "N'Djamena",
    "Chile", "Santiago",
    "China", "Beijing",
    "Colombia", "Bogotá",
    "Costa Rica", "San José",
    "Croatia", "Zagreb",
    "Cuba", "Havana",
    "Cyprus", "Nicosia",
    "Czech Republic", "Prague",
    "Côte d'Ivoire", "Yamoussoukro",
    "Democratic Republic of the Congo", "Kinshasa",
    "Denmark", "Copenhagen",
    "Djibouti", "Djibouti",
    "Dominican Republic", "Santo Domingo",
    "Ecuador", "Quito",
    "Egypt", "Cairo",
    "El Salvador", "San Salvador",
    "Estonia", "Tallinn",
    "Ethiopia", "Addis Ababa",
    "Faroe Islands", "Tórshavn",
    "Fiji", "Suva",
    "Finland", "Helsinki",
    "France", "Paris",
    "Gabon", "Libreville",
    "Gambia", "Banjul",
    "Georgia", "Tbilisi",
    "Germany", "Berlin",
    "Ghana", "Accra",
    "Gibraltar", "Gibraltar",
    "Greece", "Athens",
    "Greenland", "Nuuk",
    "Guam", "Hagåtña",
    "Guatemala", "Guatemala City",
    "Guinea", "Conakry",
    "Guinea-Bissau", "Bissau",
    "Haiti", "Port-au-Prince",
    "Honduras", "Tegucigalpa",
    "Hungary", "Budapest",
    "Iceland", "Reykjavík",
    "India", "New Delhi",
    "Indonesia", "Jakarta",
    "Iran", "Tehran",
    "Iraq", "Baghdad",
    "Ireland", "Dublin",
    "Israel", "Jerusalem",
    "Italy", "Rome",
    "Jamaica", "Kingston",
    "Japan", "Tokyo",
    "Jordan", "Amman",
    "Kazakhstan", "Astana",
    "Kenya", "Nairobi",
    "Kosovo", "Pristina",
    "Kuwait", "Kuwait City",
    "Kyrgyzstan", "Bishkek",
    "Laos", "Vientiane",
    "Latvia", "Riga",
    "Lebanon", "Beirut",
    "Libya", "Tripoli",
    "Liechtenstein", "Vaduz",
    "Lithuania", "Vilnius",
    "Luxembourg", "Luxembourg",
    "Macedonia", "Skopje",
    "Madagascar", "Antananarivo",
    "Malaysia", "Kuala Lumpur",
    "Maldives", "Malé",
    "Mali", "Bamako",
    "Malta", "Valletta",
    "Mauritania", "Nouakchott",
    "Mexico", "Mexico City",
    "Moldova", "Chisinau",
    "Monaco", "Monaco",
    "Mongolia", "Ulaanbaatar",
    "Montenegro", "Podgorica",
    "Morocco", "Rabat",
    "Mozambique", "Maputo",
    "Myanmar", "Naypyidaw",
    "Nepal", "Kathmandu",
    "Netherlands", "Amsterdam",
    "New Zealand", "Wellington",
    "Nicaragua", "Managua",
    "Niger", "Niamey",
    "Nigeria", "Abuja",
    "Norway", "Oslo",
    "Oman", "Muscat",
    "Pakistan", "Islamabad",
    "Palestine", "Jerusalem",
    "Panama", "Panama City",
    "Paraguay", "Asunción",
    "Peru", "Lima",
    "Philippines", "Manila",
    "Poland", "Warsaw",
    "Portugal", "Lisbon",
    "Puerto Rico", "San Juan",
    "Qatar", "Doha",
    "Republic of China (Taiwan)", "Taipei",
    "Republic of the Congo", "Brazzaville",
    "Romania", "Bucharest",
    "Russia", "Moscow",
    "Saudi Arabia", "Riyadh",
    "Scotland", "Edinburgh",
    "Senegal", "Dakar",
    "Serbia", "Belgrade",
    "Sierra Leone", "Freetown",
    "Singapore", "Singapore",
    "Slovakia", "Bratislava",
    "Slovenia", "Ljubljana",
    "Solomon Islands", "Honiara",
    "Somalia", "Mogadishu",
    "South Africa", "Pretoria",
    "South Korea", "Seoul",
    "Spain", "Madrid",
    "Sri Lanka", "Sri Jayawardenapura Kotte",
    "Sudan", "Khartoum",
    "Suriname", "Paramaribo",
    "Swaziland", "Mbabane",
    "Sweden", "Stockholm",
    "Switzerland", "Bern",
    "Syria", "Damascus",
    "Tajikistan", "Dushanbe",
    "Tanzania", "Dodoma",
    "Thailand", "Bangkok",
    "Togo", "Lomé",
    "Trinidad and Tobago", "Port of Spain",
    "Tunisia", "Tunis",
    "Turkey", "Ankara",
    "Turkmenistan", "Ashgabat",
    "Uganda", "Kampala",
    "Ukraine", "Kiev",
    "United Arab Emirates", "Abu Dhabi",
    "United Kingdom; England", "London",
    "United States", "Washington, D.C.",
    "Uruguay", "Montevideo",
    "Uzbekistan", "Tashkent",
    "Venezuela", "Caracas",
    "Vietnam", "Hanoi",
    "Wales", "Cardiff",
    "Yemen", "Sanaá",
    "Zambia", "Lusaka",
    "Zimbabwe", "Harare"
)